name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  next-version:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Release
        uses: mehdi-ra/main-develop-semver@a72752066126879a5ca505f0d0a733ed9e9602e1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          releaseTitle: Auto release
